version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Adm1n1str4t0r
      POSTGRES_USER: Admin
      POSTGRES_DB: Alice
    ports:
    - 5432:5432
  app:
    image: zerophiel/alice:latest
    restart: always
    ports:
    - 8080:8080
  frontend:
    image: zerophiel/nemesis:latest
    restart: always
    ports:
    - 80:80